### ISSUE TITLE
Error 10054

### ISSUE THREAD

**Issue by max12202** [sriyegna/Pikaptcha#11]
Hi running the bot on windows 10 after some account creation i run into this issue:

> Step 1: Verifying age using birthday: 1985-03-06
> Step 2: Entering account details
> Starting autosolve recaptcha
> We will wait 10 seconds for captcha to be solved by 2captcha
> Captcha still not solved, waiting another 10 seconds.
> Solved captcha
> Traceback (most recent call last):
>   File "C:\Python27\Scripts\pikaptcha-script.py", line 9, in <module>
>     load_entry_point('Pikaptcha==0.1', 'console_scripts', 'pikaptcha')()
>   File "c:\python27\lib\site-packages\pikaptcha\console.py", line 96, in entry
>     account_info = pikaptcha.random_account(args.username, args.password, args.email, args.birthday, args.plusmail, args.recaptcha)
>   File "c:\python27\lib\site-packages\pikaptcha\accountcreator.py", line 241, in random_account
>     account_created = create_account(try_username, password, try_email, try_birthday, captchakey2)
>   File "c:\python27\lib\site-packages\pikaptcha\accountcreator.py", line 194, in create_account
>     user.submit()
>   File "c:\python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 83, in submit
>     self._execute(Command.SUBMIT_ELEMENT)
>   File "c:\python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 461, in _execute
>     return self._parent.execute(command, params)
>   File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 234, in execute
>     response = self.command_executor.execute(driver_command, params)
>   File "c:\python27\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 401, in execute
>     return self._request(command_info[0], url, body=data)
>   File "c:\python27\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 471, in _request
>     resp = opener.open(request, timeout=self._timeout)
>   File "c:\python27\lib\urllib2.py", line 429, in open
>     response = self._open(req, data)
>   File "c:\python27\lib\urllib2.py", line 447, in _open
>     '_open', req)
>   File "c:\python27\lib\urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "c:\python27\lib\urllib2.py", line 1228, in http_open
>     return self.do_open(httplib.HTTPConnection, req)
>   File "c:\python27\lib\urllib2.py", line 1201, in do_open
>     r = h.getresponse(buffering=True)
>   File "c:\python27\lib\httplib.py", line 1136, in getresponse
>     response.begin()
>   File "c:\python27\lib\httplib.py", line 453, in begin
>     version, status, reason = self._read_status()
>   File "c:\python27\lib\httplib.py", line 409, in _read_status
>     line = self.fp.readline(_MAXLINE + 1)
>   File "c:\python27\lib\socket.py", line 480, in readline
>     data = self._sock.recv(self._rbufsize)
> socket.error: [Errno 10054] An existing connection was forcibly closed by the remote host

**Comment by sriyegna** [comment]
What happened here is that the remote host dropped the connection with you. What would typically happen here is that it would be retried but urllib2 doesn't seem to do that. 

Can you upgrade your pikaptcha? pip install --upgrade pikaptcha

**Comment by sriyegna** [comment]
Error should be handled now. Upgrade pikaptcha and try to reproduce please.
