### ISSUE TITLE
Chromedriver stalls immediately after being called

### ISSUE THREAD

**Issue by phr34k0** [sriyegna/Pikaptcha#13]
Do you always need to close your browser first before script execution?

![image](https://cloud.githubusercontent.com/assets/13272249/17882305/4be3325a-693e-11e6-9fee-2a72b148db34.png)

lol

OS - Kali rolling

**Comment by sriyegna** [comment]
What?

**Comment by phr34k0** [comment]
And it gets stuck there till you close browser and restart pikacaptcha 

![image](https://cloud.githubusercontent.com/assets/13272249/17882434/fce36bb0-693e-11e6-8017-fdbb5a0d8dff.png)

**Comment by phr34k0** [comment]
https://bugs.chromium.org/p/chromedriver/issues/detail?id=733

**Comment by sriyegna** [comment]
I don't this this is a bug with pikaptcha. In your issue, you haven't even begun to make a request to the POGO url which already has https prefixed.

Essentially it just stalls after calling driver = webdriver.Chrome(). I am not sure how to reproduce this so I can't investigate or try and find a workaround,

**Comment by phr34k0** [comment]
Script works if browser is closed and it pika will open and do all those accounts for you but if the browser is open one gets stuck with that bug. My guess is probably because on linux some of us had to run chrome with --user-data-dir and --no-sandbox argument

**Comment by sriyegna** [comment]
Can you give me more information about your environment so I can attempt to duplicate this tomorrow?

**Comment by phr34k0** [comment]
Sure. I'm on Kali Linux with Google-Chrome Version 52.0.2743.116 (64-bit) and using latest Chromedriver 2.23  http://chromedriver.storage.googleapis.com/index.html?path=2.23/


![image](https://cloud.githubusercontent.com/assets/13272249/17883436/15f8c338-6945-11e6-871e-0e7f6a8ec011.png)

**Comment by sriyegna** [comment]
Alright, I don't know exactly how to debug this. If someone else would like to fix this, I would be delighted. I'm not very good with linux.

**Comment by crckdns** [comment]
well, this bug isn't only in linux "available" ..
windows10 here~
same behavior:
`c:\Users\crckdns\Desktop>pikaptcha -c 2 -p yyy -m xxx@gmail.com -av True -gp xxx -l xxx,yyy -of pkgo
Making account #1
Attempting to create user xxx:yyy. Opening browser...
Generic Exception: Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pikaptcha\console.py", line 159, in entry
    account_info = pikaptcha.random_account(username, args.password, args.email, args.birthday, args.plusmail, args.recaptcha, args.captchatimeout)
  File "c:\python27\lib\site-packages\pikaptcha\accountcreator.py", line 231, in random_account
    account_created = create_account(try_username, password, try_email, try_birthday, captchakey2, captchatimeout)
  File "c:\python27\lib\site-packages\pikaptcha\accountcreator.py", line 94, in create_account
    driver = webdriver.Chrome()
  File "c:\python27\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "c:\python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: session not created exception
from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"11120.1","isDefault":true},"id":1,"name":"","origin":"://"}
  (Session info: chrome=54.0.2840.6)
  (Driver info: chromedriver=2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129),platform=Windows NT 10.0.14393 x86_64)`

**Comment by aduljr** [comment]
Looks more like an issue with the chrome webdriver than the application. I have not yet come across this issue myself. I see in chrome driver you can enable more debugging into a log. That may prove useful.

driver = webdriver.Chrome(executable_path="D:\\chromedriver.exe", service_args=["--verbose", "--log-path=D:\\qc1.log"])

**Comment by totalsoft2015** [comment]
[https://www.youtube.com/watch?v=KpTdj6-2wRw](url)
Video fix chrome with error no-sandbox kali rolling, hope you can fix

**Comment by phr34k0** [comment]
@totalsoft2015 Just close your browser mate and let them scripts pass
