### ISSUE TITLE
ReCAPTCHA wait window too short or error code not registered successfully

### ISSUE THREAD

**Issue by joshuakoh7** [sriyegna/Pikaptcha#15]
I've ran the script for 5 hours and only one account was successfully created using -r. Either the script isn't waiting long enough or it is taking a null reply to be the solved captcha.

"Starting autosolve recaptcha
We will wait 10 seconds for captcha to be solved by 2captcha
Captcha still not solved, waiting another 10 seconds.
Solved captcha"

**Comment by sriyegna** [comment]
I am not sure what it happening here. Especially when only 1 acct worked. Join us on discord so I can debug this. I haven't seen anyone else have this issue. Are you sure you ran it correctly?

**Comment by joshuakoh7** [comment]
There was only one captcha correctly solved (only charged once under recaptcha). Is there any way to increase the sleep duration or retries?

**Comment by sriyegna** [comment]
default sleep duration is like 1000s... If you set one, then you may run into issues. Something else is going on.

**Comment by joshuakoh7** [comment]
Is there any way to dump the output? A -V mode or something?

**Comment by joshuakoh7** [comment]
Where is the discord anyway?

**Comment by sriyegna** [comment]
https://discord.gg/PfX5B7F

I am going to close this as invalid as the default timeout is 1000s and you are able to set the timeout. I believe some other issue is occuring here.
