### ISSUE TITLE
Segmentation fault !

### ISSUE THREAD

**Issue by bornbygoogle** [sriyegna/Pikaptcha#16]
pip install git+https://github.com/sriyegna/pikaptcha
Collecting git+https://github.com/sriyegna/pikaptcha
  Cloning https://github.com/sriyegna/pikaptcha to /tmp/pip-hOqr1I-build
Collecting requests[security]==2.10.0 (from Pikaptcha===0.1)
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting six==1.10.0 (from Pikaptcha===0.1)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting selenium==2.53.6 (from Pikaptcha===0.1)
  Using cached selenium-2.53.6-py2.py3-none-any.whl
Collecting pyOpenSSL>=0.13; extra == "security" (from requests[security]==2.10.0->Pikaptcha===0.1)
  Using cached pyOpenSSL-16.0.0-py2.py3-none-any.whl
Collecting ndg-httpsclient; extra == "security" (from requests[security]==2.10.0->Pikaptcha===0.1)
Collecting pyasn1; extra == "security" (from requests[security]==2.10.0->Pikaptcha===0.1)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting cryptography>=1.3 (from pyOpenSSL>=0.13; extra == "security"->requests[security]==2.10.0->Pikaptcha===0.1)
Collecting setuptools>=11.3 (from cryptography>=1.3->pyOpenSSL>=0.13; extra == "security"->requests[security]==2.10.0->Pikaptcha===0.1)
  Using cached setuptools-26.0.0-py2.py3-none-any.whl
Collecting ipaddress (from cryptography>=1.3->pyOpenSSL>=0.13; extra == "security"->requests[security]==2.10.0->Pikaptcha===0.1)
  Using cached ipaddress-1.0.16-py27-none-any.whl
Collecting enum34 (from cryptography>=1.3->pyOpenSSL>=0.13; extra == "security"->requests[security]==2.10.0->Pikaptcha===0.1)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting idna>=2.0 (from cryptography>=1.3->pyOpenSSL>=0.13; extra == "security"->requests[security]==2.10.0->Pikaptcha===0.1)
  Using cached idna-2.1-py2.py3-none-any.whl
Collecting cffi>=1.4.1 (from cryptography>=1.3->pyOpenSSL>=0.13; extra == "security"->requests[security]==2.10.0->Pikaptcha===0.1)
  Using cached cffi-1.7.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pycparser (from cffi>=1.4.1->cryptography>=1.3->pyOpenSSL>=0.13; extra == "security"->requests[security]==2.10.0->Pikaptcha===0.1)
Installing collected packages: setuptools, ipaddress, six, pyasn1, enum34, idna, pycparser, cffi, cryptography, pyOpenSSL, ndg-httpsclient, requests, selenium, Pikaptcha
  Running setup.py install for Pikaptcha ... done
Successfully installed Pikaptcha-0.1 cffi-1.7.0 cryptography-1.4 enum34-1.1.6 idna-2.1 ipaddress-1.0.16 ndg-httpsclient-0.4.2 pyOpenSSL-16.0.0 pyasn1-0.1.9 pycparser-2.14 requests-2.10.0 selenium-2.53.6 setuptools-26.0.0 six-1.10.0
Segmentation fault

OS : Kali

**Comment by sriyegna** [comment]
I am not very familiar with Linux so I don't know what exactly is going on here. Perhaps someone else with more knowledge can provide their input.

**Comment by bornbygoogle** [comment]
found out, you need root privilege or just run the command inside virtual env !
