### ISSUE TITLE
''-of'' and ''-sn'' not recognized 

### ISSUE THREAD

**Issue by NiKTaMeR** [sriyegna/Pikaptcha#18]
commands not recognized in latest version.

**Comment by sriyegna** [comment]
Post your exact command please

**Comment by Guile3home** [comment]
it is work for me currently in latest version.

**Comment by NiKTaMeR** [comment]
pikaptcha -c 10 -u xxxxx -sn 2 -p wxxxxxxx -m pyxxxxxxxx@gmail.com -av True -gp mxxxxxxx -l 45.xx,-73.xx -of pkgo

**Comment by sriyegna** [comment]
This is the same as https://github.com/sriyegna/Pikaptcha/issues/14

not sure why -sn isn't working for you. Try running it without the location for now, or edit it into the script and recompile.
