### ISSUE TITLE
UnboundLocalError: local variable 'captchabal' referenced before assignment

### ISSUE THREAD

**Issue by Mickey32111** [sriyegna/Pikaptcha#21]
Hey, I'm having trouble getting Pikaptcha to work on Mac OS X 10.12 Beta.

Whenever I run it, no matter what the arguments are, I get the following error:
`Traceback (most recent call last):
File "/usr/local/bin/pikaptcha", line 11, in <module>
load_entry_point('Pikaptcha==0.1', 'console_scripts', 'pikaptcha')()
File "/usr/local/lib/python2.7/site-packages/pikaptcha/console.py", line 135, in entry
if _verify_settings({'args':args, 'balance':captchabal}):
UnboundLocalError: local variable 'captchabal' referenced before assignment`

Any help will be appreciated.

**Comment by FranManre** [comment]
It was working yesterday, today i started facing some problems with google email verification:

```
Generic Exception: Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\pikaptcha\console.py", line 141, in entry
    email_verify(args.plusmail, args.googlepass)
  File "build\bdist.win-amd64\egg\pikaptcha\gmailv.py", line 43, in email_verify
    M = imaplib.IMAP4_SSL('imap.gmail.com')
  File "C:\Python27\lib\imaplib.py", line 1166, in __init__
    IMAP4.__init__(self, host, port)
  File "C:\Python27\lib\imaplib.py", line 173, in __init__
    self.open(host, port)
  File "C:\Python27\lib\imaplib.py", line 1178, in open
    self.sslobj = ssl.wrap_socket(self.sock, self.keyfile, self.certfile)
  File "C:\Python27\lib\ssl.py", line 933, in wrap_socket
    ciphers=ciphers)
  File "C:\Python27\lib\ssl.py", line 601, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)
```

ive uninstalled all, from pgoapi and pikaptcha to everything including git, python... ive reinstalled all and now i have this:

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\pikaptcha-script.py", line 9, in <module>
    load_entry_point('Pikaptcha==0.1', 'console_scripts', 'pikaptcha')()
  File "c:\python27\lib\site-packages\pikaptcha\console.py", line 135, in entry
    if _verify_settings({'args':args, 'balance':captchabal}):
UnboundLocalError: local variable 'captchabal' referenced before assignment
```

**Comment by mrbiggmd** [comment]
Same here.

Traceback (most recent call last):
  File "C:\Python27\Scripts\pikaptcha-script.py", line 11, in <module>
    load_entry_point('Pikaptcha==0.1', 'console_scripts', 'pikaptcha')()
  File "c:\python27\lib\site-packages\pikaptcha\console.py", line 135, in entry
    if _verify_settings({'args':args, 'balance':captchabal}):
UnboundLocalError: local variable 'captchabal' referenced before assignment

**Comment by atticusm** [comment]
Same

**Comment by FranManre** [comment]
if helps someone, ive downloaded a previous release (https://github.com/sriyegna/Pikaptcha/tree/e0d1c2a572f41a65aea7662316b16909e7a2ca2a), then unzipped it, opened a cmd on the folder and done `python setup.py install`, it works until verification, then added the autoverify script from here https://gist.github.com/sebastienvercammen/e7e0e9e57db246d7f941b789d8508186 following their steps and now im doing bulk of accs without verify, when i finish i verify it on a row, is the way to do this works that ive found

**Comment by kiraacorsac** [comment]
Fixed it in #22

**Comment by Mickey32111** [comment]
Doesn't fix for me. @kiraacorsac

**Comment by jakeb16** [comment]
I just tried this out and I'm having the same issue

**Comment by jakeb16** [comment]
updating the console.py fixes the problem line 120 and 135
there is a space between parse and _
and the variable captchabal wasnt defined

 args = parse_arguments(sys.argv[1:])
    if args.recaptcha != None:
        captchabal = "Failed"
        while(captchabal == "Failed"):
            captchabal = openurl("http://2captcha.com/res.php?key=" + args.recaptcha + "&action=getbalance")
        print("Your 2captcha balance is: " + captchabal)
        print("This run will cost you approximately: " + str(float(args.count)*0.003))
    else:
        captchabal = "Empty"

**Comment by sriyegna** [comment]
I just merged the PR. Sorry, was out all day.
