### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by max12202** [sriyegna/Pikaptcha#28]
Would be nice if i could use a proxy for tos accepting, or for every task pikaptcha do.
I know that i can use proxifier or software like that but i think that a built-in proxy system would be better.

P.S: all the issues that regards me were successfully fixed, great work man!

**Comment by kiraacorsac** [comment]
Implemented in #29. Only for ToS, I don't see any reason (yet) for the rest of the tasks.

**Comment by max12202** [comment]
Yea i know the only thing that matter are tos for proxy because of niantic's bans. Anyway thank you i'll close this issues.

**Comment by kiraacorsac** [comment]
You should wait if the PR gets merged or not before closing ;)

**Comment by max12202** [comment]
Ah, ok i'll reopen then. Sorry I'm new to github world i don't know exactly how does it works.

**Comment by kiraacorsac** [comment]
Well you wrote the feature request regarding master branch, so until the master branch gets the feature or the admins decide to close the issue for other reason, there is no reason to close it. I'm not an admin, I just thought the  feature is a good idea so I implemented it and posted it as a PR. Sriyegna may come, say "Your code smells" and reject the PR, therefore leaving the issue relevant.

**Comment by sriyegna** [comment]
I am not able to test the pr for the next few days. Kiraa, have you tested it and ensured it doesn't break anything TOS related? Code looks fine

**Comment by kiraacorsac** [comment]
I have tested the following usecases:

```
pikaptcha 
pikaptcha -px working_proxy
pikaptcha -px bad_proxy
```

And it works as expected.

//edit:
Quickly gave a try to

```
pikaptcha -px working_proxy -l 0.0,0.0
pikaptcha -l 0.0,0.0
```

and it works as well.

**Comment by max12202** [comment]
what if the proxy have user and pass authentication?

**Comment by kiraacorsac** [comment]
The proxying iteslf is handled by python `urllib2` in `pgoapi`, so `pikaptcha -px username:password@proxy:port` should work.

**Comment by max12202** [comment]
I tried to use proxy implemented in the new update with the scheme username:password@proxy:port and after declaring that it will accept the ToS he throw this exception:

```
Generic Exception: Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pikaptcha\console.py", line 166, in entry
    accept_tos(account_info["username"], account_info["password"], args.location, args.proxy)
  File "c:\python27\lib\site-packages\pikaptcha\tos.py", line 10, in accept_tos
    accept_tos_helper(username, password, location, proxy)
  File "c:\python27\lib\site-packages\pikaptcha\tos.py", line 32, in accept_tos_helper
    response = api.app_simulation_login()
  File "c:\python27\lib\site-packages\pgoapi\pgoapi.py", line 158, in app_simulation_login
    response = request.call()
  File "c:\python27\lib\site-packages\pgoapi\pgoapi.py", line 241, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "c:\python27\lib\site-packages\pgoapi\rpc_api.py", line 128, in request
    response = self._make_rpc(endpoint, request_proto)
  File "c:\python27\lib\site-packages\pgoapi\rpc_api.py", line 116, in _make_rpc
    http_response = self._session.post(endpoint, data=request_proto_serialized, timeout=30)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "c:\python27\lib\site-packages\requests\adapters.py", line 370, in send
    conn = self.get_connection(request.url, proxies)
  File "c:\python27\lib\site-packages\requests\adapters.py", line 273, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "c:\python27\lib\site-packages\requests\adapters.py", line 179, in proxy_manager_for
    **proxy_kwargs)
  File "c:\python27\lib\site-packages\requests\packages\urllib3\poolmanager.py", line 284, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "c:\python27\lib\site-packages\requests\packages\urllib3\poolmanager.py", line 235, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
ProxySchemeUnknown: Not supported proxy scheme *my proxy username access*
```

**Comment by kiraacorsac** [comment]
Try to specify the protocol like this: `https://username:password@proxyurl:proxyport`. If not, can you contact me on Discord? I am not an owner of a private proxy and cannot test this (have not found a trial account too).

Also make sure the proxy is HTTPS, because SOCKS proxies are not supported yet by pgoapi, I believe.

**Comment by sriyegna** [comment]
Thanks @kiraacorsac . If you don't mind, could you post your findings here so others don't encounter the same issue.

Cheers

**Comment by max12202** [comment]
Ok everything is good now! i've formatted like @kiraacorsac said: `https://username:password@proxyurl:proxyport` and it works well now. I'm going to test this now with about 100 accounts and i'll tell you if there will be some problems.

**Comment by max12202** [comment]
Created 100 accounts with no issues so i think that the proxy option works great. Thank you @kiraacorsac  and @sriyegna for your awesome support :D
