### ISSUE TITLE
[Bug + Solution] Gmail Verification

### ISSUE THREAD

**Issue by DZisopoulos** [sriyegna/Pikaptcha#3]
Just noticed that Gmail blocks "less secure apps" from accessing the email, resulting in an error [Could not access email account] or something similar. You can check if thats the case by logging in to your GMail and checking if you have a "Sign-In attempt prevented" email in your inbox. If you do, you have to do is go to https://www.google.com/settings/u/1/security/lesssecureapps and Turn On the access to less secure apps.

**Comment by sriyegna** [comment]
Ah yes. That is true, i forgot to include that in the readme. Thank you, it will be updated.
