### ISSUE TITLE
`-ct` parameter not functional?

### ISSUE THREAD

**Issue by DoktorJ** [sriyegna/Pikaptcha#32]
I ran Pikaptcha with `-ct 90`, which should abort the account creation after 90 seconds, correct?

However, every now and then I see one that goes well past that time limit; for example, this one:

```
Starting autosolve recaptcha
We will wait 10 seconds for captcha to be solved by 2captcha
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Captcha still not solved, waiting another 10 seconds.
Solved captcha
```

As you can see, that one ran ~150 seconds before the captcha was solved.

The issue appears to be that `time.clock()` on Unix-based systems (I'm running on Mac OS X) is represented differently than on Windows, being a floating point number that seems to be related to the CPU time used by the program rather than real time.

As such, I would suggest using `int(time.time())` for the timing instead, as it will return seconds since the epoch, which is an absolute reference of time, and I believe is the same between Windows and *nix.

**Comment by sriyegna** [comment]
Sounds good. Ill implement that small change when I get my desktop set up.

**Comment by sriyegna** [comment]
Thanks for implementing the fix.

**Comment by DoktorJ** [comment]
Verified working as expected on OS X (with `-ct 90` I had one time out after the initial wait + 8 "still not solved" ticks)
