### ISSUE TITLE
[Suggestion] - Randomize interval between account creation

### ISSUE THREAD

**Issue by kbtbc** [sriyegna/Pikaptcha#35]
For example add flags, such as
UserSetMinDelay = 30
UserSetMaxDelay = 600 
Then generate random time between 30 & 600 seconds each new account.

Thanks for this tool!

**Comment by sriyegna** [comment]
Wouldn't the inconsistency in 2captcha solve times already do a similar thing? You may have a delay on top of another delay now...

**Comment by kiraacorsac** [comment]
Is there a reason for the randomization? Is PTC banning/forbidding creation of accounts when they are created too periodic? I'm asking because I'm looking to implement paralleled account creation, and don't really want to waste time if PTC is actively fighting against :)
