### ISSUE TITLE
Unbelievably slow on Win10

### ISSUE THREAD

**Issue by tsnork** [sriyegna/Pikaptcha#37]
Hi,

I use your nice tool on 2 laptops, the setup is identical according to the instructions provided here. On the laptop with Win10 it takes about 5 minutes to create a single account, every letter/number appears with a delay of about 10 seconds, on the Win7 laptop its blazingly fast.

Is there a way to debug this to provide some more info?

**Comment by sriyegna** [comment]
Please join us on discord to diagnose this. Are you saying one computer pauses 10 seconds before inputting a character into any text field?

I am not sure why that would happen. We pass the whole string to selenium who then inputs it 1 by 1. But there should be no reason for a delay at that point

**Comment by tsnork** [comment]
K, I'll be there in a few minutes.

**Comment by aduljr** [comment]
For the record it runs fairly quick on my windows 10 desktop.
