### ISSUE TITLE
Running it with Python 3.5

### ISSUE THREAD

**Issue by iluretar** [sriyegna/Pikaptcha#47]
Im trying to run the script with python 3.5 and i managed to fix all the errors i was getting and now it works fine except for the email activation , im getting this:
`if subjmsg.find("Trainer_Club_Activation") != -1:
TypeError: a bytes-like object is required, not 'str'`

in gmailv.py line 24, i tried fixing it myself but my python is veeery limited, any help would be appreciated.

**Comment by sriyegna** [comment]
I don't have any experience with Python 3.5
