### ISSUE TITLE
Captcha timeout

### ISSUE THREAD

**Issue by ardeaf** [sriyegna/Pikaptcha#5]
Timeout option would be great, as sometimes waiting for 2captcha doesn't work.

**Comment by sriyegna** [comment]
It does not. 2captcha says they provide a 100% success rate so I keep waiting. The other option would be to timeout and waste $0.003. Which option do you think is better? I can implement either. And what would be a good timeout interval.

**Comment by sriyegna** [comment]
Notreallyhere suggested allowing the user to input their timeout interval. Default being infinite. This is what I will implement unless a better suggestion arises.

**Comment by sriyegna** [comment]
Completed
