### ISSUE TITLE
Windows server

### ISSUE THREAD

**Issue by max12202** [sriyegna/Pikaptcha#8]
Hi i have a little issue, i'm trying to run Pikaptcha on a VPS (Windows server 2012).
Now the problem is that as soon i start the bot with 2captcha resolver, the cmd just stucks and don't go ahead:
![e4156641a960704fabdc4a63326bb89b](https://cloud.githubusercontent.com/assets/5462951/17841049/8e25cf22-6814-11e6-93c1-ade5d376aff4.png)
(Yeah i already waited for so long).
If i just run the command "pikaptcha" so without 2captcha resolver it works.
I think there is a problem with phantomjs, i read online that there may be a problem with ghostdriver.log creation. 

I hope you can help me. 
BTW on windows 10 it runs smoothly, thank you for your awesome job! ;-)

**Comment by WJKH** [comment]
I'm running it on Windows Server 2012 without issues.
Do you have installed everything properly?

**Comment by sriyegna** [comment]
There is a decent amount of stuff that happens before phantomjs is called. You aren't getting anywhere. My guess is that your vps is blocking 2captcha because the first thing we do is a get request for your balance

**Comment by max12202** [comment]
@WJKH I've installed all thing like on my windows 10 machine (python 2.7, git, visual c++ for python, i've fixed my path, chromedriver (even if i don't need that), chrome, phantomjs).

@sriyegna probably you're right, if phantomjs follow windows' internet options probably it's blocking 2captcha. I'm going to check later.

Thank you for your support guys.

**Comment by max12202** [comment]
I tried to reinstall everything that it needs, but didn't work. So i've disabled IE enhanced security configuration and add 2captcha.com to trusted sites, but didn't work. I've also tried to disable windows firewall but nothing to do it doesn't work. Any ideas?

**Comment by sriyegna** [comment]
I would like to make sure the problem lies with 2captcha then. Try this. Open python. Import urllib2.
print urllib2.urlopen("http://2captcha.com/res.php?key=" + args.recaptcha + "&action=getbalance").read()

Replace the recaptcha part with your key

**Comment by max12202** [comment]
Actually i've resolved the issue, there was a problem with the name of my batch file(pikaptcha.bat), i've renamed it to run.bat and then it works. 
Thank you for your effort to help me ;-).
P.S: if you can help me with the other issue I would be very grateful :-)
